/*
 * Copyright (c) 2019-2029, Dreamlu 卢春梦 (596392912@qq.com & www.dreamlu.net).
 * <p>
 * Licensed under the GNU LESSER GENERAL PUBLIC LICENSE 3.0;
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * http://www.gnu.org/licenses/lgpl.html
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package net.dreamlu.mica.auto.factories;

import lombok.experimental.UtilityClass;
import net.dreamlu.mica.auto.common.MultiSetMap;

import java.io.BufferedWriter;
import java.io.IOException;
import java.io.OutputStream;
import java.io.OutputStreamWriter;
import java.nio.charset.Charset;
import java.nio.charset.StandardCharsets;
import java.util.Set;
import java.util.StringJoiner;

/**
 * spring boot 自动化配置工具类
 *
 * @author L.cm
 */
@UtilityClass
class FactoriesFiles {
	private static final Charset UTF_8 = StandardCharsets.UTF_8;

	/**
	 * 写出 spring.factories 文件
	 * @param factories factories 信息
	 * @param output 输出流
	 * @throws IOException 异常信息
	 */
	static void writeFactoriesFile(MultiSetMap<String, String> factories,
								   OutputStream output) throws IOException {
		BufferedWriter writer = new BufferedWriter(new OutputStreamWriter(output, UTF_8));
		writer.write("# Generated by mica-auto www.dreamlu.net\n");
		Set<String> keySet = factories.keySet();
		for (String key : keySet) {
			Set<String> values = factories.get(key);
			if (values == null || values.isEmpty()) {
				continue;
			}
			writer.write(key);
			writer.write("=\\\n  ");
			StringJoiner joiner = new StringJoiner(",\\\n  ");
			for (String value : values) {
				joiner.add(value);
			}
			writer.write(joiner.toString());
			writer.newLine();
		}
		writer.flush();
		output.close();
	}

	/**
	 * 写出 spring-devtools.properties
	 * @param projectName 项目名
	 * @param output 输出流
	 * @throws IOException 异常信息
	 */
	static void writeDevToolsFile(String projectName,
								  OutputStream output) throws IOException {
		BufferedWriter writer = new BufferedWriter(new OutputStreamWriter(output, UTF_8));
		// restart.include.mica-cloud=/mica-cloud[\\w-]+\.jar
		String format = "restart.include.%s=/%s[\\\\w-]+\\.jar";
		writer.write("# Generated by mica-auto www.dreamlu.net\n");
		writer.write(String.format(format, projectName, projectName));
		writer.flush();
		output.close();
	}
}
